---
dotfiles_repo: ""
dotfiles_version: "main"
dotfiles_install_script: ""
dotfiles_links: []
dotfiles_backup_existing: true
target_user: "{{ ansible_facts['user_id'] }}"
target_home: "{{ '/root' if target_user == 'root' else '/home/' ~ target_user }}"
dotfiles_dest: "{{ target_home }}/.dotfiles"
